source 'https://rubygems.org'

# GitHub Pages
gem 'github-pages', group: :jekyll_plugins

# Jekyll plugins
group :jekyll_plugins do
  gem 'jekyll-remote-theme'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
end

# Development tools
group :development do
  gem 'html-proofer'
  gem 'webrick', '~> 1.7'
end

# Windows and JRuby compatibility
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'wdm', '~> 0.1.1', platforms: [:mingw, :mswin, :x64_mingw]